version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/usr/local/var/postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/todo-app
    ports:
      - "5000:5000"
    depends_on:
      - db